### ISSUE TITLE
QueueManager.ts出现空指针错误

### ISSUE THREAD

**Issue by semmy2010** [xiyuan-fengyu/ppspider#11]
忘记怎么操作了，启动的时候会出现以下空指针错误
```

2019-10-17 21:18:13.582 warn QueueManager.<anonymous> (e:\github\ppspider_example\node_modules\ppspider\src\spider\manager\QueueManager.ts:362:20) TypeError: Cannot read property 'successNum' of undefined
    at QueueManager.<anonymous> (e:\github\ppspider_example\node_modules\ppspider\src\spider\manager\QueueManager.ts:312:52)
    at Generator.next (<anonymous>)
    at fulfilled (e:\github\ppspider_example\node_modules\ppspider\lib\spider\manager\QueueManager.js:13:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by xiyuan-fengyu** [comment]
这个是重启时运行状态的cache文件解析失败了，无法恢复之前保存的运行状态，最好能提供一下代码，如果能重现就更好
